name: Auto Update

on:
  schedule:
    - cron: "15 0/8 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: npm run update
      - run: |
          git config user.name 'The Tracker'
          git config user.email ''
          git add .
          git commit -m 'auto-update'
          git remote set-url origin https://SilentDepth:$GITHUB_TOKEN@github.com/SilentDepth/notion-client-src-tracker.git
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
