name: Auto Update

on:
  schedule:
    - cron: "0 0/6 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - run: |
          yarn
          yarn run update
      - run: |
          git config user.name 'Bot Penguin'
          git config user.email ''
          git remote set-url origin https://SilentDepth:$GITHUB_TOKEN@github.com/SilentDepth/notion-client-src-tracker.git
          git add .
          git commit -m '`[ -f UPDATED ] && cat UPDATED`' && git push origin HEAD:master || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
